// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"database/sql"
)

type ManagementRoute struct {
	ID          string
	RouteName   sql.NullString
	Origin      sql.NullString
	Destination sql.NullString
}
